# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_moeda'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='moeda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moeda', to='financeiro.Moeda'),
        ),
    ]
