# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20170820_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='day_by_day',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
