# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20170930_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='produto_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
