# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_moeda'),
        ('cadastro', '0007_produto_produto_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='moeda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='financeiro.Moeda'),
        ),
    ]
