# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 21:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_produto_moeda'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acomodacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Opcional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoAcomodacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('acomodacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Acomodacao')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cidade')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Produto')),
            ],
        ),
        migrations.AddField(
            model_name='produto',
            name='acomodacoes',
            field=models.ManyToManyField(blank=True, null=True, through='cadastro.ProdutoAcomodacao', to='cadastro.Acomodacao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='cidades',
            field=models.ManyToManyField(blank=True, null=True, through='cadastro.ProdutoCidade', to='cadastro.Cidade'),
        ),
        migrations.AddField(
            model_name='produto',
            name='opcionais',
            field=models.ManyToManyField(blank=True, null=True, to='cadastro.Opcional'),
        ),
    ]
