# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 06:01
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djangosige.apps.cadastro.models.escola


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('cadastro', '0009_auto_20171001_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastro.Pessoa')),
                ('logo_file', models.ImageField(blank=True, default='imagens/logo.png', null=True, upload_to=djangosige.apps.cadastro.models.escola.logo_directory_path)),
                ('cnae', models.CharField(blank=True, max_length=10, null=True)),
                ('iest', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'permissions': (('view_escola', 'Can view escola'),),
                'verbose_name': 'Escola',
            },
            bases=('cadastro.pessoa',),
        ),
        migrations.CreateModel(
            name='MinhaEscola',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minha_escola', to='cadastro.Escola')),
                ('m_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escola_usuario', to='login.Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Passageiro',
            fields=[
                ('pessoa_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cadastro.Pessoa')),
                ('limite_de_credito', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, null=True)),
                ('indicador_ie', models.CharField(choices=[('1', 'Contribuinte ICMS'), ('2', 'Contribuinte isento de Inscrição'), ('9', 'Não Contribuinte')], default='9', max_length=1)),
                ('id_estrangeiro', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'permissions': (('view_passageiro', 'Can view passageiro'),),
                'verbose_name': 'Passageiro',
            },
            bases=('cadastro.pessoa',),
        ),
    ]
