# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_escola_minhaescola_passageiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola', to='cadastro.Escola'),
        ),
    ]
