# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_passageiro_escola'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passageiro',
            name='escola',
        ),
        migrations.AddField(
            model_name='passageiro',
            name='escola_passageiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escola_passageiro', to='cadastro.Escola'),
        ),
    ]
