# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20171013_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoProduto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Documento',
            },
        ),
        migrations.AddField(
            model_name='produto',
            name='documentos',
            field=models.ManyToManyField(blank=True, null=True, to='cadastro.DocumentoProduto'),
        ),
    ]
