# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_auto_20171024_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageiro',
            name='matricula',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
