# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20170820_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='movimentar_estoque',
            field=models.BooleanField(default=False),
        ),
    ]
