# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_passageiro_escola'),
        ('vendas', '0003_auto_20171013_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='pacote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pacote', to='cadastro.Produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venda_passageiro', to='cadastro.Cliente'),
        ),
    ]
