# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 07:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20171013_0456'),
        ('vendas', '0005_auto_20171013_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='passageiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venda_passageiro', to='cadastro.Passageiro'),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='bandeira',
            field=models.CharField(choices=[('01', 'AMEX'), ('02', 'MASTERCARD'), ('03', 'VISA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='cartao',
            name='tipo',
            field=models.CharField(choices=[('01', 'CREDITO'), ('02', 'DEBITO')], max_length=3),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venda_cliente', to='cadastro.Cliente'),
        ),
    ]
