# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-13 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20171013_0456'),
        ('vendas', '0006_auto_20171013_0456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passageiro', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=16, null=True)),
                ('observacao', models.CharField(blank=True, max_length=500, null=True)),
                ('escola', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escola_prospect', to='cadastro.Escola')),
            ],
        ),
    ]
