# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 14:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_auto_20171013_0456'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendas', '0007_prospect'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoProspect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_contato', models.CharField(blank=True, choices=[('1', 'Visita'), ('2', 'Reunião'), ('3', 'Proposta'), ('4', 'Ligação'), ('5', 'Email')], max_length=1, null=True)),
                ('observacao', models.CharField(max_length=500)),
                ('emissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='prospect',
            name='cliente_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='escola_prospect', to='cadastro.Cliente'),
        ),
        migrations.AddField(
            model_name='contatoprospect',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='prospect', to='vendas.Prospect'),
        ),
    ]
