# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0010_auto_20171023_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoprospect',
            name='emissor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prospect',
            name='cliente',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prospect',
            name='passageiro',
            field=models.CharField(max_length=200),
        ),
    ]
