# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-23 18:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0013_prospect_emissor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prospect',
            name='emissor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
