# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0014_auto_20171023_1621'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prospect',
            options={'permissions': (('view_prospect', 'Can view prospect'),), 'verbose_name': 'Prospect'},
        ),
    ]
