# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0015_auto_20171024_1505'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatoprospect',
            options={'permissions': (('view_contatoprospect', 'Can view Contato prospect'),), 'verbose_name': 'Contato Prospect'},
        ),
    ]
