# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0017_auto_20171024_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contatoprospect',
            name='observacao',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contatoprospect',
            name='tipo_contato',
            field=models.CharField(choices=[('1', 'Visita'), ('2', 'Reunião'), ('3', 'Proposta'), ('4', 'Ligação'), ('5', 'WhatsApp'), ('6', 'Email')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
