# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 23:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0018_auto_20171025_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='contatoprospect',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 10, 28, 23, 0, 51, 466103, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
